<?php
/**
 * @category   Bluethink
 * @package    Bluethink_Comptest
 * @author     mohit.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bluethink\Comptest\Block;

use Magento\Framework\View\Element\Template\Context;
use Bluethink\Comptest\Model\ComptestFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Comptest View block
 */
class ComptestView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Comptest
     */
    protected $_comptest;
    public function __construct(
        Context $context,
        ComptestFactory $comptest,
        FilterProvider $filterProvider
    ) {
        $this->_comptest = $comptest;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Bluethink Comptest Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $comptest = $this->_comptest->create();
        $singleData = $comptest->load($id);
        if($singleData->getComptestId() && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}