<?php
/**
 * @category   Bluethink
 * @package    Bluethink_Comptest
 * @author     mohit.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Bluethink\Comptest\Block;

use Magento\Framework\View\Element\Template\Context;
use Bluethink\Comptest\Model\ComptestFactory;
/**
 * Comptest List block
 */
class ComptestListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Comptest
     */
    protected $_comptest;
    public function __construct(
        Context $context,
        ComptestFactory $comptest
    ) {
        $this->_comptest = $comptest;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Bluethink Comptest Module List Page'));
        
        if ($this->getComptestCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'bluethink.comptest.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getComptestCollection()
            );
            $this->setChild('pager', $pager);
            $this->getComptestCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getComptestCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $comptest = $this->_comptest->create();
        $collection = $comptest->getCollection();
        $collection->addFieldToFilter('status','1');
        //$comptest->setOrder('comptest_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}